import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'user-stories',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/termux',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: 'Using Hermes',
      collapsed: true,
      items: [
        'user-guide/cli',
        'user-guide/tui',
        'user-guide/windows-native',
        'user-guide/windows-wsl-quickstart',
        'user-guide/configuration',
        'user-guide/configuring-models',
        'user-guide/sessions',
        'user-guide/profiles',
        'user-guide/profile-distributions',
        'user-guide/git-worktrees',
        'user-guide/docker',
        'user-guide/security',
        'user-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'user-guide/features/overview',
        'user-guide/features/tool-gateway',
        {
          type: 'category',
          label: 'Core',
          items: [
            'user-guide/features/tools',
            'user-guide/features/skills',
            'user-guide/features/lsp',
            'user-guide/features/curator',
            'user-guide/features/memory',
            'user-guide/features/memory-providers',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/plugins',
            'user-guide/features/built-in-plugins',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          items: [
            'user-guide/features/cron',
            'user-guide/features/delegation',
            'user-guide/features/kanban',
            'user-guide/features/codex-app-server-runtime',
            'user-guide/features/kanban-tutorial',
            'user-guide/features/kanban-worker-lanes',
            'user-guide/features/goals',
            'user-guide/features/code-execution',
            'user-guide/features/hooks',
            'user-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: 'Media & Web',
          items: [
            'user-guide/features/voice-mode',
            'user-guide/features/web-search',
            'user-guide/features/browser',
            'user-guide/features/computer-use',
            'user-guide/features/vision',
            'user-guide/features/image-generation',
            'user-guide/features/tts',
          ],
        },
        {
          type: 'category',
          label: 'Management',
          items: [
            'user-guide/features/web-dashboard',
            'user-guide/features/extending-the-dashboard',
            'user-guide/features/subscription-proxy',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            'user-guide/features/rl-training',
            'user-guide/features/spotify',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          collapsed: true,
          items: [
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Messaging Platforms',
      collapsed: true,
      items: [
        'user-guide/messaging/index',
        'user-guide/messaging/telegram',
        'user-guide/messaging/discord',
        'user-guide/messaging/slack',
        'user-guide/messaging/whatsapp',
        'user-guide/messaging/signal',
        'user-guide/messaging/email',
        'user-guide/messaging/sms',
        'user-guide/messaging/homeassistant',
        'user-guide/messaging/mattermost',
        'user-guide/messaging/matrix',
        'user-guide/messaging/dingtalk',
        'user-guide/messaging/feishu',
        'user-guide/messaging/wecom',
        'user-guide/messaging/wecom-callback',
        'user-guide/messaging/weixin',
        'user-guide/messaging/bluebubbles',
        'user-guide/messaging/qqbot',
        'user-guide/messaging/yuanbao',
        'user-guide/messaging/teams',
        'user-guide/messaging/teams-meetings',
        'user-guide/messaging/msgraph-webhook',
        'user-guide/messaging/line',
        'user-guide/messaging/open-webui',
        'user-guide/messaging/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/providers',
        'user-guide/features/mcp',
        'user-guide/features/acp',
        'user-guide/features/api-server',
        'user-guide/features/honcho',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
        'user-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Tutorials',
      collapsed: true,
      items: [
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/build-a-hermes-plugin',
        'guides/automate-with-cron',
        'guides/cron-script-only',
        'guides/automation-templates',
        'guides/cron-troubleshooting',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/github-pr-review-agent',
        'guides/webhook-github-pr-review',
        'guides/migrate-from-openclaw',
        'guides/aws-bedrock',
        'guides/azure-foundry',
        'guides/microsoft-graph-app-registration',
        'guides/operate-teams-meeting-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'developer-guide/architecture',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/gateway-internals',
            'developer-guide/session-storage',
            'developer-guide/provider-runtime',
          ],
        },
        {
          type: 'category',
          label: 'Extending',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/adding-platform-adapters',
            'developer-guide/memory-provider-plugin',
            'developer-guide/context-engine-plugin',
            'developer-guide/model-provider-plugin',
            'developer-guide/image-gen-provider-plugin',
            'developer-guide/video-gen-provider-plugin',
            'developer-guide/plugin-llm-access',
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: 'Internals',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/environments',
            'developer-guide/trajectory-format',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/cli-commands',
        'reference/slash-commands',
        'reference/profile-commands',
        'reference/environment-variables',
        'reference/tools-reference',
        'reference/toolsets-reference',
        'reference/mcp-config-reference',
        'reference/model-catalog',
        'reference/skills-catalog',
        'reference/optional-skills-catalog',
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
